# Generated by Django 3.1.5 on 2021-02-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url_field',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
