# Generated by Django 3.1.5 on 2021-02-12 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_category_url_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indication',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indications', to='awards.category'),
        ),
    ]
