# Generated by Django 3.1.5 on 2021-06-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awards", "0004_auto_20210217_2219"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indication",
            name="annotation",
            field=models.TextField(blank=True),
        ),
    ]
