import type { AppProps } from "next/app";
import ReactModal from "react-modal";
import "../styles/globals.css";
import AuthProvider from "../components/auth/AuthProvider";
import { QueryClient, QueryClientProvider } from "react-query";
import Head from "next/head";
import React from "react";

ReactModal.setAppElement("#__next");

const queryClient = new QueryClient();

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Aposcar</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🏆</text></svg>"
        />
      </Head>
      <div className="bg-gray-900 h-screen text-gray-50">
        <QueryClientProvider client={queryClient}>
          <AuthProvider>
            <Component {...pageProps} />
          </AuthProvider>
        </QueryClientProvider>
      </div>
    </>
  );
}
export default MyApp;
