import React from "react";
import Head from "next/head";
import MainLayout from "../components/MainLayout";
import Card from "../components/Card";

export default function Home() {
  return (
    <>
      <Head>
        <title>Aposcar</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🏆</text></svg>"
        />
      </Head>
      <main className="h-full">
        <MainLayout>
          <div className="grid grid-cols-2 p-10 pt-7 gap-7 h-full">
            <Card
              header={<div className="font-bold text-2xl">Global Ranking</div>}
            >
              home
            </Card>
            <Card header={<div className="font-bold text-2xl">Categories</div>}>
              home
            </Card>
          </div>
        </MainLayout>
      </main>
    </>
  );
}
