import React from "react";
import Navbar from "./Navbar";
import Footer from "./Footer";
import Head from "next/head";

interface Props {
  title?: string;
}

const MainLayout: React.FC<Props> = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title ?? "Aposcar"}</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🏆</text></svg>"
        />
      </Head>
      <div className="flex flex-col h-full">
        <Navbar />
        <div className="flex-1 flex-grow mt-7">{children}</div>
        <Footer />
      </div>
    </>
  );
};

export default MainLayout;
